spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/credit_db
    username: postgres
    password: "postgres"
  liquibase: classpath:liquibase/changelog.yml

